/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Prova;

/**
 *
 * @author Micro
 */
public class Gabarito extends javax.swing.JFrame {

    /**
     * Creates new form Gabarito
     */
    Prova prova = Prova.getInstance();
    public Gabarito() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblRes1 = new javax.swing.JLabel();
        lblRes2 = new javax.swing.JLabel();
        lblRes3 = new javax.swing.JLabel();
        lblRes4 = new javax.swing.JLabel();
        lblSta1 = new javax.swing.JLabel();
        lblSta2 = new javax.swing.JLabel();
        lblSta3 = new javax.swing.JLabel();
        lblSta4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        lblTempo1 = new javax.swing.JLabel();
        lblTempo2 = new javax.swing.JLabel();
        lblTempo3 = new javax.swing.JLabel();
        lblTempo4 = new javax.swing.JLabel();
        btnQ1 = new javax.swing.JButton();
        btnQ4 = new javax.swing.JButton();
        btnQ2 = new javax.swing.JButton();
        btnQ3 = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnRanking = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel1.setText("Questão ");

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel2.setText("Status");

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel3.setText("Resposta");

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel4.setText("Tempo/Questão");

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel5.setText("Prova");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addComponent(jLabel3)
                .addGap(205, 205, 205)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(127, 127, 127)
                .addComponent(jLabel4)
                .addGap(81, 81, 81))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel6.setText("1");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 21));

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel7.setText("2");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 21));

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel8.setText("3");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel9.setText("4 ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        lblRes1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPanel2.add(lblRes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        lblRes2.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPanel2.add(lblRes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, 20));

        lblRes3.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPanel2.add(lblRes3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        lblRes4.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPanel2.add(lblRes4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        lblSta1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPanel2.add(lblSta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, -1));

        lblSta2.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPanel2.add(lblSta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, -1, 20));

        lblSta3.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPanel2.add(lblSta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, -1, -1));

        lblSta4.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPanel2.add(lblSta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, -1, -1));

        jLabel10.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel10.setText(" Matemática e suas tecnologias");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel11.setText(" Matemática e suas tecnologias");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        jLabel12.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel12.setText("Ciências da Natureza e suas tecnologias");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, 20));

        jLabel13.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel13.setText("Ciências da Natureza e suas tecnologias");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        btnSalvar.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnSalvar.setText("Salvar Respostas");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, -1, -1));

        lblTempo1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPanel2.add(lblTempo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, -1, -1));

        lblTempo2.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPanel2.add(lblTempo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 90, -1, -1));

        lblTempo3.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPanel2.add(lblTempo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 160, -1, -1));

        lblTempo4.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPanel2.add(lblTempo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 230, -1, -1));

        btnQ1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        btnQ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQ1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnQ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 20, 160, -1));

        btnQ4.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        btnQ4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQ4ActionPerformed(evt);
            }
        });
        jPanel2.add(btnQ4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 220, 160, -1));

        btnQ2.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        btnQ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQ2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnQ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 80, 160, -1));

        btnQ3.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        btnQ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQ3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnQ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 150, 160, -1));

        btnVoltar.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnVoltar.setText("Voltar ao menu");
        btnVoltar.setEnabled(false);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnRanking.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnRanking.setText("Ranking");
        btnRanking.setEnabled(false);
        btnRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRankingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1178, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158)
                        .addComponent(btnRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnRanking))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        String respostas [] = prova.getRespostas();
        
        if(respostas[0] != "X"){
            lblRes1.setText("Letra "+respostas[0]);
            //lblSta1.setForeground(Color.GREEN);
            lblSta1.setText(" Respondido");
            btnQ1.setText("Mudar resposta");
        }else{
            lblRes1.setText("   -");
            lblSta1.setForeground(Color.RED);
            lblSta1.setText("Sem resposta");
            btnQ1.setText("Responder");
        }
        
        if(respostas[1] != "X"){
            lblRes2.setText("Letra "+respostas[1]);
            //lblSta2.setForeground(Color.GREEN);
            lblSta2.setText(" Respondido");
            btnQ2.setText("Mudar resposta");
        }else{
            lblRes2.setText("   -");
            lblSta2.setForeground(Color.RED);
            lblSta2.setText("Sem resposta");
            btnQ2.setText("Responder");
        }
        
        if(respostas[2] != "X"){
            lblRes3.setText("Letra "+respostas[2]);
            //lblSta3.setForeground(Color.GREEN);
            lblSta3.setText(" Respondido");
            btnQ3.setText("Mudar resposta");
        }else{
            lblRes3.setText("   -");
            lblSta3.setForeground(Color.RED);
            lblSta3.setText("Sem resposta");
            btnQ3.setText("Responder");
        }
        
        if(respostas[3] != "X"){
            lblRes4.setText("Letra "+respostas[3]);
            //lblSta4.setForeground(Color.GREEN);
            lblSta4.setText(" Respondido");
            btnQ4.setText("Mudar resposta");
        }else{
            lblRes4.setText("   -");
            lblSta4.setForeground(Color.RED);
            lblSta4.setText("Sem resposta");
            btnQ4.setText("Responder");
        }
        
        lblTempo1.setText(Integer.toString(prova.tempo[0].min)+"m"+
                        Integer.toString(prova.tempo[0].seg)+"s");
        lblTempo2.setText(Integer.toString(prova.tempo[1].min)+"m"+
                        Integer.toString(prova.tempo[1].seg)+"s");
        lblTempo3.setText(Integer.toString(prova.tempo[2].min)+"m"+
                        Integer.toString(prova.tempo[2].seg)+"s");
        lblTempo4.setText(Integer.toString(prova.tempo[3].min)+"m"+
                        Integer.toString(prova.tempo[3].seg)+"s");
        
     
    }//GEN-LAST:event_formWindowActivated

    private void btnQ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQ1ActionPerformed
        // TODO add your handling code here:
            prova.revisao[0] = true;
            Questao01 questao01 = new Questao01();
            questao01.setVisible(true);
            dispose();
    }//GEN-LAST:event_btnQ1ActionPerformed

    private void btnQ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQ2ActionPerformed
        // TODO add your handling code here:
            prova.revisao[1] = true;
            Questao02 questao02 = new Questao02();
            questao02.setVisible(true);
            dispose();
    }//GEN-LAST:event_btnQ2ActionPerformed

    private void btnQ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQ3ActionPerformed
        // TODO add your handling code here:
            prova.revisao[2] = true;
            Questao03 questao03 = new Questao03();
            questao03.setVisible(true);
            dispose();
    }//GEN-LAST:event_btnQ3ActionPerformed

    private void btnQ4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQ4ActionPerformed
        // TODO add your handling code here:
            prova.revisao[3] = true;
            Questao04 questao04 = new Questao04();
            questao04.setVisible(true);
            dispose();
    }//GEN-LAST:event_btnQ4ActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        String respostas [] = prova.getRespostas();
        
        if(respostas[0] == "A") prova.acertos++;
        if(respostas[1] == "E") prova.acertos++;
        if(respostas[2] == "A") prova.acertos++;
        if(respostas[3] == "C") prova.acertos++;
                
        JOptionPane.showMessageDialog(null, "RESPOSTAS ENVIADAS", 
                    "SUCESSO", JOptionPane.INFORMATION_MESSAGE); 
        btnQ1.setEnabled(false);
        btnQ2.setEnabled(false);
        btnQ3.setEnabled(false);
        btnQ4.setEnabled(false);
        btnVoltar.setEnabled(true);
        btnRanking.setEnabled(true);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        prova.limpar();
        SignUp signUp = new SignUp();
        signUp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRankingActionPerformed
        // TODO add your handling code here:
        Ranking ranking = new Ranking();
        ranking.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRankingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gabarito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gabarito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gabarito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gabarito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gabarito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQ1;
    private javax.swing.JButton btnQ2;
    private javax.swing.JButton btnQ3;
    private javax.swing.JButton btnQ4;
    private javax.swing.JButton btnRanking;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblRes1;
    private javax.swing.JLabel lblRes2;
    private javax.swing.JLabel lblRes3;
    private javax.swing.JLabel lblRes4;
    private javax.swing.JLabel lblSta1;
    private javax.swing.JLabel lblSta2;
    private javax.swing.JLabel lblSta3;
    private javax.swing.JLabel lblSta4;
    private javax.swing.JLabel lblTempo1;
    private javax.swing.JLabel lblTempo2;
    private javax.swing.JLabel lblTempo3;
    private javax.swing.JLabel lblTempo4;
    // End of variables declaration//GEN-END:variables
}
