/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import model.Prova;

/**
 *
 * @author Micro
 */
public class Questao02 extends javax.swing.JFrame {

    /**
     * Creates new form Questao02
     */
    Timer t;
    Prova prova = Prova.getInstance();
    public Questao02() {
        initComponents();
        lblRelogio.setText("Tempo: "+Integer.toString(prova.tempo[0].min)+"m"+
                        Integer.toString(prova.tempo[0].seg)+"s");
        StringBuilder sb = new StringBuilder();
        sb.append("<html><body>");
        sb.append("<sup>");
        sb.append("1");
        sb.append("</sup>");
        sb.append("&frasl;");
        sb.append("<sub>");
        sb.append("2");
        sb.append("</sub>");
        sb.append("</html></body>");
        
        lblA.setText(sb.toString());
        lblB.setText(sb.toString());
        lblC.setText(sb.toString());
        lblD.setText(sb.toString());
        lblA4.setText(sb.toString());
        lblB4.setText(sb.toString());
        lblC4.setText(sb.toString());
        lblD4.setText(sb.toString());
        
        sb.setLength(0);
        sb.append("<html><body>");
        sb.append("<sup>");
        sb.append("1");
        sb.append("</sup>");
        sb.append("&frasl;");
        sb.append("<sub>");
        sb.append("4");
        sb.append("</sub>");
        sb.append("</html></body>");
        
        lblA2.setText(sb.toString());
        lblB2.setText(sb.toString());
        lblC2.setText(sb.toString());
        lblD2.setText(sb.toString());
        lblA5.setText(sb.toString());
        lblB5.setText(sb.toString());
        lblC5.setText(sb.toString());
        lblD5.setText(sb.toString());
        
     
        t = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                
                lblRelogio.setText("Tempo: "+Integer.toString(prova.tempo[1].min)+"m"+
                        Integer.toString(prova.tempo[1].seg)+"s");
                prova.tempo[1].passaSegundo();
            }
        });
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rBtnA = new javax.swing.JRadioButton();
        rBtnB = new javax.swing.JRadioButton();
        rBtnC = new javax.swing.JRadioButton();
        rBtnD = new javax.swing.JRadioButton();
        rBtnE = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnRevisar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lblA = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        lblC = new javax.swing.JLabel();
        lblD = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblA2 = new javax.swing.JLabel();
        lblB2 = new javax.swing.JLabel();
        lblC2 = new javax.swing.JLabel();
        lblD2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblA3 = new javax.swing.JLabel();
        lblB3 = new javax.swing.JLabel();
        lblC3 = new javax.swing.JLabel();
        lblD3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblB4 = new javax.swing.JLabel();
        lblC4 = new javax.swing.JLabel();
        lblD4 = new javax.swing.JLabel();
        lblA4 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        lblD5 = new javax.swing.JLabel();
        lblA5 = new javax.swing.JLabel();
        lblB5 = new javax.swing.JLabel();
        lblC5 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblRelogio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Um aluno registrou as notas bimestrais de algumas de suas disciplinas numa tabela. Ele observou que as entradas numéricas da tabela formavam uma matriz 4x4, e que poderia calcular as médias anuais dessas disciplinas usando produto de matrizes. Todas as provas possuíam o mesmo peso, e a tabela que ele conseguiu é mostrada a seguir.");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 440, 152));

        jTable1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Matemática", "   5,9", "   6,2", "    4,5", "   5,5"},
                {"Português", "   6,6", "   7,1", "    6,5", "   8,4"},
                {"Geografia", "   8,6", "   6,8", "    7,8", "   9,0"},
                {"História", "   6,2", "   5,6", "    5,9", "   7,7"}
            },
            new String [] {
                "", "1º Bimestre", "2º Bimestre", "3º Bimestre", "4º Bimestre"
            }
        ));
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 440, 95));

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel3.setText("Para obter essas médias, ele multiplicou");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel4.setText("a matriz obtida a partir da tabela por");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 28, -1, -1));

        buttonGroup1.add(rBtnA);
        rBtnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnAActionPerformed(evt);
            }
        });
        jPanel2.add(rBtnA, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 84, -1, -1));

        buttonGroup1.add(rBtnB);
        jPanel2.add(rBtnB, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 140, -1, -1));

        buttonGroup1.add(rBtnC);
        jPanel2.add(rBtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 216, -1, -1));

        buttonGroup1.add(rBtnD);
        jPanel2.add(rBtnD, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, -1, -1));

        buttonGroup1.add(rBtnE);
        jPanel2.add(rBtnE, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, -1, -1));

        jLabel5.setText("A");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        jLabel6.setText("B");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

        jLabel7.setText("C");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

        jLabel8.setText("D");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, -1, -1));

        jLabel9.setText("E");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, -1, -1));

        btnRevisar.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        btnRevisar.setText("Revisar Depois");
        btnRevisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevisarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRevisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 140, -1));

        btnSalvar.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 380, 100, -1));

        jLabel10.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel10.setText("|");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 71, -1, -1));

        lblA.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblA.setText("f1");
        jPanel2.add(lblA, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, -1, -1));

        lblB.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblB.setText("f1");
        jPanel2.add(lblB, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, -1, -1));

        lblC.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblC.setText("f1");
        jPanel2.add(lblC, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, -1, -1));

        lblD.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblD.setText("f1");
        jPanel2.add(lblD, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, -1, -1));

        jLabel11.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel11.setText("|");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, -1, -1));

        lblA2.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblA2.setText("f1");
        jPanel2.add(lblA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, -1));

        lblB2.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblB2.setText("f1");
        jPanel2.add(lblB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, -1, -1));

        lblC2.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblC2.setText("f1");
        jPanel2.add(lblC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, -1, -1));

        lblD2.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblD2.setText("f1");
        jPanel2.add(lblD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, -1, -1));

        jLabel13.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel13.setText("|");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, -1, -1));

        jLabel14.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel14.setText("|");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, -1, -1));

        lblA3.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblA3.setText("1");
        jPanel2.add(lblA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));

        lblB3.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblB3.setText("1");
        jPanel2.add(lblB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, -1, -1));

        lblC3.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblC3.setText("1");
        jPanel2.add(lblC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, -1, -1));

        lblD3.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblD3.setText("1");
        jPanel2.add(lblD3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, -1, -1));

        jLabel17.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel17.setText("|");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, -1, -1));

        jLabel20.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel20.setText("|");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 310, -1, -1));

        jLabel21.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel21.setText("|");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, -1, 32));

        lblB4.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblB4.setText("f1");
        jPanel2.add(lblB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 110, -1, -1));

        lblC4.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblC4.setText("f1");
        jPanel2.add(lblC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 140, -1, -1));

        lblD4.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblD4.setText("f1");
        jPanel2.add(lblD4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, -1, -1));

        lblA4.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblA4.setText("f1");
        jPanel2.add(lblA4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, -1, -1));

        jLabel22.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel22.setText("|");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, -1, 38));

        jLabel23.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel23.setText("|");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 160, -1, 34));

        jLabel24.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel24.setText("|");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, -1, -1));

        jLabel25.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel25.setText("|");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 100, -1, 32));

        jLabel16.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel16.setText("|");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, -1, -1));

        jLabel19.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel19.setText("|");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, -1, -1));

        jLabel26.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel26.setText("|");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, -1, -1));

        jLabel27.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel27.setText("|");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, -1, -1));

        jLabel28.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel28.setText("|");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, -1, -1));

        jLabel29.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel29.setText("|");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, -1, -1));

        jLabel15.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel15.setText("|");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 120, -1, -1));

        jLabel30.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel30.setText("|");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, -1, 34));

        jLabel31.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel31.setText("|");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, -1, 34));

        jLabel32.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel32.setText("|");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 140, -1, 34));

        jLabel33.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel33.setText("|");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, -1, 34));

        jLabel34.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel34.setText("|");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, -1, -1));

        jLabel35.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel35.setText("|");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 310, -1, -1));

        jLabel36.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel36.setText("|");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, -1, -1));

        jLabel37.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel37.setText("|");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 260, -1, -1));

        jLabel38.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel38.setText("|");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 280, -1, -1));

        lblD5.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblD5.setText("f1");
        jPanel2.add(lblD5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 320, -1, -1));

        lblA5.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblA5.setText("f1");
        jPanel2.add(lblA5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 230, -1, -1));

        lblB5.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblB5.setText("f1");
        jPanel2.add(lblB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 260, -1, -1));

        lblC5.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblC5.setText("f1");
        jPanel2.add(lblC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 290, -1, -1));

        jLabel39.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel39.setText("|");
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, -1, -1));

        jLabel40.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel40.setText("|");
        jPanel2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 220, -1, -1));

        jLabel41.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel41.setText("|");
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 240, -1, -1));

        jLabel42.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel42.setText("|");
        jPanel2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 260, -1, -1));

        jLabel43.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel43.setText("|");
        jPanel2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 280, -1, -1));

        jLabel44.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel44.setText("|");
        jPanel2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, -1, -1));

        jLabel45.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel45.setText("|");
        jPanel2.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 300, -1, -1));

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel1.setText("Questão 2");

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel2.setText("Prova: Matemática e suas tecnologias");

        lblRelogio.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        lblRelogio.setText("Tempo: 0m0s");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(74, 74, 74)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                .addComponent(lblRelogio)
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRelogio, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Prova prova = Prova.getInstance();
        if(rBtnA.isSelected()){
            prova.setRespostas("A", 1);
        }else if(rBtnB.isSelected()){
            prova.setRespostas("B", 1);
        }else if(rBtnC.isSelected()){
            prova.setRespostas("C", 1);
        }else if(rBtnD.isSelected()){
            prova.setRespostas("D", 1);
        }else if(rBtnE.isSelected()){
            prova.setRespostas("E", 1);
        }
        if(buttonGroup1.getSelection() == null){
            JOptionPane.showMessageDialog(rootPane, "Selecione uma opção",
                "ERRO", JOptionPane.ERROR_MESSAGE, null);
        }else if(!prova.revisao[1]){
            Questao03 questao03 = new Questao03();
            questao03.setVisible(true);
            dispose();
            t.stop();
        }else{
            Gabarito gabarito = new Gabarito();
            gabarito.setVisible(true);
            dispose();
            t.stop();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void rBtnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBtnAActionPerformed

    private void btnRevisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevisarActionPerformed
        // TODO add your handling code here:
        if(!prova.revisao[1]){
            Questao03 questao03 = new Questao03();
            questao03.setVisible(true);
            dispose();
            t.stop();
        }else{
            Gabarito gabarito = new Gabarito();
            gabarito.setVisible(true);
            dispose();
            t.stop();
        }
    }//GEN-LAST:event_btnRevisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Questao02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Questao02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Questao02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Questao02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Questao02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRevisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblA2;
    private javax.swing.JLabel lblA3;
    private javax.swing.JLabel lblA4;
    private javax.swing.JLabel lblA5;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblB2;
    private javax.swing.JLabel lblB3;
    private javax.swing.JLabel lblB4;
    private javax.swing.JLabel lblB5;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblC2;
    private javax.swing.JLabel lblC3;
    private javax.swing.JLabel lblC4;
    private javax.swing.JLabel lblC5;
    private javax.swing.JLabel lblD;
    private javax.swing.JLabel lblD2;
    private javax.swing.JLabel lblD3;
    private javax.swing.JLabel lblD4;
    private javax.swing.JLabel lblD5;
    private javax.swing.JLabel lblRelogio;
    private javax.swing.JRadioButton rBtnA;
    private javax.swing.JRadioButton rBtnB;
    private javax.swing.JRadioButton rBtnC;
    private javax.swing.JRadioButton rBtnD;
    private javax.swing.JRadioButton rBtnE;
    // End of variables declaration//GEN-END:variables
}
